### ISSUE TITLE
Feature request: Python 3 support

### ISSUE THREAD

**Issue by alok** [mptre/vim-printf#2]
For python 3, turn a line into a (correctly indented) `print("{}".format(...))` (or the older printf-based syntax `print("%s" % (x))`.

**Comment by mptre** [comment]
How about the following pattern?

```vim
autocmd FileType python let b:printf_pattern = 'print("%s" % (%s))'
```

**Comment by Ran4** [comment]
The `.format` version is likely preferred for Python3 users, as it's more powerful. Both are used, but the main argument against `.format` is usually that it takes slightly longer to write... which is averted with this plugin.

**Comment by mptre** [comment]
Would this be the preferred outcome using `.format`?

```python
x, y
print("x={}, y={}".format(x, y))
```

I have limited experience with Python.

**Comment by Ran4** [comment]
I think that looks good! I would personally prefer

```python
x, y
print("x: {}, y: {}".format(x, y))
```

though. Whitespace is much preferred in Pythonland, and when I see ` x = ...` I think of default arguments or a value being set (e.g. `"#setting x = 4 in order to..."`).

**Comment by mptre** [comment]
@Alok @Ran4 lets move the discussion to #3.
